name: Notify Telegram on Pull Request Events

on:
  pull_request:
    types: [opened, closed]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send notification to Telegram
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          if [ "${{ github.event.action }}" == "opened" ]; then
            MESSAGE="New pull request opened: ${{ github.event.pull_request.title }} by ${{ github.event.pull_request.user.login }}. View it here: ${{ github.event.pull_request.html_url }}"
          elif [ "${{ github.event.action }}" == "closed" ] && [ "${{ github.event.pull_request.merged }}" == "true" ]; then
            MESSAGE="Pull request merged: ${{ github.event.pull_request.title }} by ${{ github.event.pull_request.user.login }}. View it here: ${{ github.event.pull_request.html_url }}"
          else
            MESSAGE="Pull request closed: ${{ github.event.pull_request.title }} by ${{ github.event.pull_request.user.login }}. View it here: ${{ github.event.pull_request.html_url }}"
          fi

          curl -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" -d "chat_id=${CHAT_ID}" -d "text=${MESSAGE}"
